set_nozzle_temperature:
  name: Set nozzle temperature
  description: Set the nozzle target temperature through Moonraker.
  fields:
    entity_id:
      name: Entity
      description: Any entity belonging to the target Creality Ender-3 V3 device.
      required: true
      selector:
        entity:
          integration: creality_ender3_v3
    temperature:
      name: Temperature
      description: Target nozzle temperature in Celsius.
      required: true
      example: 200
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: C
          mode: box

set_bed_temperature:
  name: Set bed temperature
  description: Set the bed target temperature through Moonraker.
  fields:
    entity_id:
      name: Entity
      description: Any entity belonging to the target Creality Ender-3 V3 device.
      required: true
      selector:
        entity:
          integration: creality_ender3_v3
    temperature:
      name: Temperature
      description: Target bed temperature in Celsius.
      required: true
      example: 60
      selector:
        number:
          min: 0
          max: 130
          unit_of_measurement: C
          mode: box

cooldown:
  name: Cool down
  description: Turn off the nozzle and bed heaters.
  fields:
    entity_id:
      name: Entity
      description: Any entity belonging to the target Creality Ender-3 V3 device.
      required: true
      selector:
        entity:
          integration: creality_ender3_v3
